// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	go_wahoo "github.com/saktibimantara/go-wahoo"
	mock "github.com/stretchr/testify/mock"
)

// IWahoo is an autogenerated mock type for the IWahoo type
type IWahoo struct {
	mock.Mock
}

// GetAccessToken provides a mock function with given fields: code
func (_m *IWahoo) GetAccessToken(code string) (*go_wahoo.TokenResponse, *go_wahoo.RequestError) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessToken")
	}

	var r0 *go_wahoo.TokenResponse
	var r1 *go_wahoo.RequestError
	if rf, ok := ret.Get(0).(func(string) (*go_wahoo.TokenResponse, *go_wahoo.RequestError)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *go_wahoo.TokenResponse); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_wahoo.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *go_wahoo.RequestError); ok {
		r1 = rf(code)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*go_wahoo.RequestError)
		}
	}

	return r0, r1
}

// GetAuthenticateURL provides a mock function with given fields:
func (_m *IWahoo) GetAuthenticateURL() (*string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuthenticateURL")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func() (*string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: refreshToken
func (_m *IWahoo) RefreshToken(refreshToken string) (*go_wahoo.TokenResponse, *go_wahoo.RequestError) {
	ret := _m.Called(refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *go_wahoo.TokenResponse
	var r1 *go_wahoo.RequestError
	if rf, ok := ret.Get(0).(func(string) (*go_wahoo.TokenResponse, *go_wahoo.RequestError)); ok {
		return rf(refreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) *go_wahoo.TokenResponse); ok {
		r0 = rf(refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_wahoo.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *go_wahoo.RequestError); ok {
		r1 = rf(refreshToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*go_wahoo.RequestError)
		}
	}

	return r0, r1
}

// NewIWahoo creates a new instance of IWahoo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIWahoo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IWahoo {
	mock := &IWahoo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
