name: Build and Test

on:
  push:
    branches:
      - setup-golangci


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Build
        run: go build -v ./...

      - name: Linter
        uses: golangci/golangci-lint-action@v6
        with:
            version: latest
            github_token: ${{ secrets.GITHUB_TOKEN }}
            only-new-issues: true
            args: "run ./... --fix"

      - name: Test
        run: go test -v ./...